version: "3.9"

# NOTE: If you want to connect db from SQL Management studio :
# Server name: <SERVER_IP>, 1433
# Authentication : SQL Server Authentication
# Login : sa
# Password : PAEc6#UU$Ds8m%L@UpaSe$2tX5%hGN3wGy7QVS
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest 
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "PAEc6#UU$Ds8m%L@UpaSe$2tX5%hGN3wGy7QVS"
      ACCEPT_EULA: "Y"

  api:
    container_name: "api"
    volumes:
      - api-data:/app/wwwroot
    # restart: always
    build:
      context: ./backend
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - "sql-server-db"
    environment:
      SQL_SERVER_NAME: "sql-server-db"
      SQL_DATABASE: "master"
      SQL_USER: "sa"
      SQL_PASSWORD: "PAEc6#UU$Ds8m%L@UpaSe$2tX5%hGN3wGy7QVS"
      VIRTUAL_HOST: "api.wesale.az"

  web-admin:
    container_name: "web-admin"
    volumes:
      - web-admin-data:/app/wwwroot
    build:
      context: ./backend
      dockerfile: Web/Dockerfile
    ports:
      - "3306:80"
    depends_on:
      - "sql-server-db"
    environment:
      SQL_SERVER_NAME: "sql-server-db"
      SQL_DATABASE: "master"
      SQL_USER: "sa"
      SQL_PASSWORD: "PAEc6#UU$Ds8m%L@UpaSe$2tX5%hGN3wGy7QVS"
      VIRTUAL_HOST: "cevmin.wesale.az"

  web-client:
    container_name: "web-client"
    volumes:
      - web-client-data:/app/assets
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: "wesale.az"

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  api-data:
  web-admin-data:
  web-client-data:
