version: "3.9"

services:

  wesale-api:
    container_name: "wesale-api" 
    restart: always
    build:
      context: ./wesale_backend
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"

  wesale-web-admin:
    container_name: "wesale-web-admin"
    restart: always
    build:
      context: ./wesale_backend
      dockerfile: Web/Dockerfile
    ports:
      - "3306:80"

  wesale-web-client:
    container_name: "wesale-web-client"
    restart: always
    build:
      context: ./wesale_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"